### ISSUE TITLE
Updating a cf_app fail with "Server error, status code: 404, error code: 10000, message: Unknown request"

### ISSUE THREAD

**Issue by pedrodparkes** [mevansam/terraform-provider-cf#143] opened 2018-09-20 15:02 UTC
Deployment happens successfully but when we change the 
url
to new value (new app), it never deploy it.

Terraform log:
```
cf_app.appname: Modifying... (ID: 3102e368-e228-453f-8d5c-39875e818499)
  url: "file:///home/user/appname.jar" => "file:///home/user/appname2.jar"
cf_app.appname: Still modifying... (ID: 3102e368-e228-453f-8d5c-39875e818499, 10s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* cf_app.appname: 1 error(s) occurred:

* cf_app.appname: Server error, status code: 404, error code: 10000, message: Unknown request
```

application log shows:
```
   2018-09-20T16:42:51.03+0200 [API/4] OUT Uploading bits for app with guid 3102e368-e228-453f-8d5c-39875e818499
   2018-09-20T16:43:44.26+0200 [API/8] OUT Uploading bits for app with guid 3102e368-e228-453f-8d5c-39875e818499
```

Fail happens in 10 seconds so it may be a problem with un-implemented in the plugin timeouts functionality.

**Comment by pedrodparkes** [comment] 2018-09-21 08:32
Debug log shows next:
```
REQUEST: [2018-09-20T18:12:32+02:00]
GET /v2/jobs/89dc5c1b-b617-4eb9-b234-952ec2dac352 HTTP/1.1
Host: <pcfhost>
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 0.0.0-unknown-version / linux



RESPONSE: [2018-09-20T18:12:32+02:00]
HTTP/1.1 200 OK
Connection: close
Content-Length: 167
Content-Type: application/json;charset=utf-8
Date: Thu, 20 Sep 2018 16:12:32 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: b0df24ae-0f84-4cf1-4f4a-a2b43a0fe74e::e3fb2e3a-6010-492c-bb01-616f9846e6ba

{
  "metadata": {
    "guid": "0",
    "created_at": "1970-01-01T00:00:00Z",
    "url": "/v2/jobs/0"
  },
  "entity": {
    "guid": "0",
    "status": "finished"
  }
}

REQUEST: [2018-09-20T18:12:32+02:00]
POST /v2/apps/3102e368-e228-453f-8d5c-39875e818499/restage HTTP/1.1
Host: <host>
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 0.0.0-unknown-version / linux



RESPONSE: [2018-09-20T18:12:32+02:00]
HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 102
Content-Type: application/json;charset=utf-8
Date: Thu, 20 Sep 2018 16:12:32 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 673fe58b-565e-4c90-6305-2e8286599d28::eee3a991-a3e1-4202-90cf-349c7554f5a4

{
  "description": "App has not finished staging",
  "error_code": "CF-NotStaged",
  "code": 170002
}


REQUEST: [2018-09-20T18:12:32+02:00]
GET /v2/apps/ HTTP/1.1
Host: <host>
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 0.0.0-unknown-version / linux



RESPONSE: [2018-09-20T18:12:32+02:00]
HTTP/1.1 404 Not Found
Connection: close
Content-Length: 86
Content-Type: application/json;charset=utf-8
Date: Thu, 20 Sep 2018 16:12:32 GMT
Server: nginx
X-Cascade: pass
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 3ccac9a9-4d28-4610-5914-d887229ebd43::d5e33be2-87b3-4515-a34f-7b6f60a228c9

{
  "description": "Unknown request",
  "error_code": "CF-NotFound",
  "code": 10000
}
```

**Comment by jcarrothers-sap** [comment] 2018-09-21 23:30
Please confirm, but I am assuming you are using v0.9.8 of the provider, since this is the most recent release.
If so, then this problem has been fixed on our dev branch by #118

**Comment by pedrodparkes** [comment] 2018-09-24 14:12
Can you provide a bin file for Linux amd64?

**Comment by gberche-orange** [comment] 2018-09-25 15:13
thanks @pedrodparkes for reporting this problem. I'm closing for now until you/we can reproduce on the latest `dev` branch. We should provide shortly new binaires in upcoming release, see #113 Feel free to reopen then

**Closed by gberche-orange** 2018-09-25 15:13 UTC
Labels: invalid
