### ISSUE TITLE
Application Update fails

### ISSUE THREAD

**Issue by samedguener** [mevansam/terraform-provider-cf#32] opened 2018-02-22 14:36 UTC
Terraform detects a plan change in a cf_application resource, uploads it, but fails starting it. It seems like the provider tries to start/restart the application, while it is restaging. After initiating a manual restart, the application successfully starts.

I have already proposed a fix for this in [#22](https://github.com/mevansam/terraform-provider-cf/pull/22).

Logs:

>   REQUEST: [<date>]
>   POST /v2/apps/a13a7e29-273a-4213-aa05-6b68acafa473/restage HTTP/1.1
>   Host: <host>
>   Accept: application/json
>   Authorization: [PRIVATE DATA HIDDEN]
>   Connection: close
>   Content-Type: application/json
>   User-Agent: go-cli 0.0.0-unknown-version / linux
> 
>   RESPONSE: [<date>]
>   HTTP/1.1 400 Bad Request
>   Connection: close
>   Content-Length: 102
>   Content-Type: application/json;charset=utf-8
>   Date: <date>
>   Server: nginx
>   X-Content-Type-Options: nosniff
>   X-Ratelimit-Limit: 80000
>   X-Ratelimit-Remaining: 79864
>   X-Ratelimit-Reset: 1513253212
>   X-Vcap-Request-Id: a2f45160-c72d-4bb9-438a-587d16421fed::a0d99008-b645-4967-8d31-ba6dff8ef47f
> 
>   { "description": "App has not finished staging", "error_code": "CF-NotStaged", "code": 170002 }
>

**Comment by gberche-orange** [comment] 2018-02-26 10:30
Thanks for reporting this issue. 

> Terraform detects a plan change in a cf_application resource

Can you please clarify the scenario ? The [cf-app](https://github.com/mevansam/terraform-provider-cloudfoundry/blob/master/website/docs/r/app.html.markdown) resource does not have a service plan attribute. Do you mean a plan upgrade on a service_instance resource instead ?

**Comment by samedguener** [comment] 2018-02-26 10:33
Hi @gberche-orange ,

with the term 'plan change' I mean the behavior of Terraform in terms of configuration changes. If any attribute changes (such as name of the application), Terraform will see this as a plan change and try to update the application. But that's exactly what is not working.

Best,
Samed

**Comment by jcarrothers-sap** [comment] 2018-04-26 23:36
@gberche-orange I'm running into this issue as well.  When the provider calls the restage endpoint after uploading the new binary package, the CF throws a 400 status code because the re-stage is already pending rather than something more graceful.  Did this ever actually work?  Has there been a behaviour change in CF?

The worst part of this is, is that even though the staging process is already pending, CF could take many hours (days?) before it decides to actually get to the pending request.  As mentioned above, calling the restage endpoint simply throws an error in this case, rather than doing something helpful like prompting the pending operation to occur immediately.

The CF CLI gets around this by literally stopping and then starting a running application during a "cf push".  Unfortunately, this seems to be the only way to actually prompt the staging process to relibably happen in any kind of reasonable time frame.  During my experiments in the last few days I have once seen the staging process start within a couple minutes, on its own, but every other time I've waited 10+ minutes to once 12+ hours and not seen the staging process complete on its own.

I'm likely to going to change the provider to behave like the CF CLI and restart a running application after  a binary upload in order to work around this.

**Comment by jcarrothers-sap** [comment] 2018-04-27 23:35
I've got a potential fix for this here #79, but I'm not done fully testing it and it may evolve as it gets internal testing in the next week or so.

**Comment by bgandon** [comment] 2018-05-29 17:06
Hi all,

I have a trace for this issue.

The test case is the following:
1. Push a `console` app in space `production` of org `easyfoundry` (that's the [Stratos v1.1.0](https://github.com/orange-cloudfoundry/stratos-ui-cf-packager/releases) I've packaged last week ;-))
2. Write a small Terraform project for these 5 resources around that `console` application: app, org, space, domain and route.
3. Run `terraform apply` to create those 5 resources.
4. Move the `terraform.tfstate` away.
5. Import the 5 resources with 5 invocations of `terraform import`. The resulting `.tfstate` is not quite the same as the one moved away at step 4.
6. Run `terraform plan` and see that the application URL has changed, so an update is planned.
7. Apply the plan, and there the `console` app is updated. With v0.9.8 we obtain a spurious `404` error, and with the `dev` branch we obtain the real `400` error.

In v0.9.8 (current master) the actual `400` error is not reported to the user because is is masked by a later `404` error. This has been fixed in `dev` branch with the work done by Xavier Marcelet  on error reporting. (Thanks @psycofdj for this!)

Here is the log (with `dev` branch, commit `ac2ba45`) of updating an app, and we can see the provider is trying to restage the app too early:

```
REQUEST: [2018-05-29T17:36:16+02:00]
PUT /v2/apps/616230f5-2064-4839-bd75-72347680904d/bits?async=true HTTP/1.1
Host: api.cf.easyfoundry.prototyp.it
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: multipart/form-data; boundary=f147d0823496675fee2f14f85ec07be3ea6792d7438e176f7fa86ce2871f
User-Agent: go-cli 0.0.0-unknown-version / darwin


[MULTIPART/FORM-DATA CONTENT HIDDEN]

RESPONSE: [2018-05-29T17:36:17+02:00]
HTTP/1.1 201 Created
Connection: close
Content-Length: 270
Content-Type: application/json;charset=utf-8
Date: Tue, 29 May 2018 15:36:17 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 8d51dac3-8d4c-4f22-4609-ead76115fe32::be434eed-b29e-4868-b8c3-f6c4c0873a9d

{
  "metadata": {
    "guid": "755c7683-0b74-47c8-a5ef-e618f28df323",
    "created_at": "2018-05-29T15:36:17Z",
    "url": "/v2/jobs/755c7683-0b74-47c8-a5ef-e618f28df323"
  },
  "entity": {
    "guid": "755c7683-0b74-47c8-a5ef-e618f28df323",
    "status": "queued"
  }
}

REQUEST: [2018-05-29T17:36:17+02:00]
GET /v2/jobs/755c7683-0b74-47c8-a5ef-e618f28df323 HTTP/1.1
Host: api.cf.easyfoundry.prototyp.it
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 0.0.0-unknown-version / darwin



RESPONSE: [2018-05-29T17:36:17+02:00]
HTTP/1.1 200 OK
Connection: close
Content-Length: 270
Content-Type: application/json;charset=utf-8
Date: Tue, 29 May 2018 15:36:17 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 97199ea5-d011-41dc-7897-604ddcdb45c2::56d5319a-0b63-4cf2-aa33-3aedf17c5598

{
  "metadata": {
    "guid": "755c7683-0b74-47c8-a5ef-e618f28df323",
    "created_at": "2018-05-29T15:36:17Z",
    "url": "/v2/jobs/755c7683-0b74-47c8-a5ef-e618f28df323"
  },
  "entity": {
    "guid": "755c7683-0b74-47c8-a5ef-e618f28df323",
    "status": "queued"
  }
}

REQUEST: [2018-05-29T17:36:22+02:00]
GET /v2/jobs/755c7683-0b74-47c8-a5ef-e618f28df323 HTTP/1.1
Host: api.cf.easyfoundry.prototyp.it
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 0.0.0-unknown-version / darwin



RESPONSE: [2018-05-29T17:36:22+02:00]
HTTP/1.1 200 OK
Connection: close
Content-Length: 271
Content-Type: application/json;charset=utf-8
Date: Tue, 29 May 2018 15:36:22 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: f0ed0017-052a-494f-7846-149f8fd67bf1::5caee905-82e9-49d8-8f69-5189f9d2ae28

{
  "metadata": {
    "guid": "755c7683-0b74-47c8-a5ef-e618f28df323",
    "created_at": "2018-05-29T15:36:17Z",
    "url": "/v2/jobs/755c7683-0b74-47c8-a5ef-e618f28df323"
  },
  "entity": {
    "guid": "755c7683-0b74-47c8-a5ef-e618f28df323",
    "status": "running"
  }
}

REQUEST: [2018-05-29T17:36:27+02:00]
GET /v2/jobs/755c7683-0b74-47c8-a5ef-e618f28df323 HTTP/1.1
Host: api.cf.easyfoundry.prototyp.it
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 0.0.0-unknown-version / darwin



RESPONSE: [2018-05-29T17:36:27+02:00]
HTTP/1.1 200 OK
Connection: close
Content-Length: 271
Content-Type: application/json;charset=utf-8
Date: Tue, 29 May 2018 15:36:27 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 6301a433-749f-4cfb-6d1c-d2ef79365321::513858c8-eeb9-458c-88fe-a6ee9017392d

{
  "metadata": {
    "guid": "755c7683-0b74-47c8-a5ef-e618f28df323",
    "created_at": "2018-05-29T15:36:17Z",
    "url": "/v2/jobs/755c7683-0b74-47c8-a5ef-e618f28df323"
  },
  "entity": {
    "guid": "755c7683-0b74-47c8-a5ef-e618f28df323",
    "status": "running"
  }
}

REQUEST: [2018-05-29T17:36:32+02:00]
GET /v2/jobs/755c7683-0b74-47c8-a5ef-e618f28df323 HTTP/1.1
Host: api.cf.easyfoundry.prototyp.it
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 0.0.0-unknown-version / darwin



RESPONSE: [2018-05-29T17:36:32+02:00]
HTTP/1.1 200 OK
Connection: close
Content-Length: 167
Content-Type: application/json;charset=utf-8
Date: Tue, 29 May 2018 15:36:32 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: dd649a35-a763-405e-5ecd-afa3daaa442e::d0979c31-3b29-4e0d-882c-1381e9f407f6

{
  "metadata": {
    "guid": "0",
    "created_at": "1970-01-01T00:00:00Z",
    "url": "/v2/jobs/0"
  },
  "entity": {
    "guid": "0",
    "status": "finished"
  }
}

REQUEST: [2018-05-29T17:36:32+02:00]
POST /v2/apps/616230f5-2064-4839-bd75-72347680904d/restage HTTP/1.1
Host: api.cf.easyfoundry.prototyp.it
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 0.0.0-unknown-version / darwin



RESPONSE: [2018-05-29T17:36:32+02:00]
HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 102
Content-Type: application/json;charset=utf-8
Date: Tue, 29 May 2018 15:36:32 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 230334b3-25cf-4c13-7e33-a3e6c968e9a6::ff12cd5e-d812-493e-bb41-c350224026e1

{
  "description": "App has not finished staging",
  "error_code": "CF-NotStaged",
  "code": 170002
}
```

I tried the fix #79 as provided by Jim Carrothers @jcarrothers-sap. (For this, I rebased his fix on top of the `dev` branch.) The result is working. No more errors.

For the record, here are the changes from `terraform plan` that are applied:

```
Terraform will perform the following actions:

  ~ cf_app.console_app
      route.#:                 "0" => "1"
      route.0.default_route:   "" => "34daec21-1d8d-48e2-9e37-902122f32419"
      timeout:                 "60" => "300"
      url:                     "https://api.cf.easyfoundry.prototyp.it/v2/apps/616230f5-2064-4839-bd75-72347680904d/download" => "file:///Users/benjamin/workspace/bosh/deployments/gstack/bosh-environment/applications/console-tf/stratos-ui-packaged.zip"

  ~ cf_route.console_route
      target.#:                "1" => "0"
      target.2639819470.app:   "616230f5-2064-4839-bd75-72347680904d" => ""
      target.2639819470.port:  "8080" => "0"

  ~ cf_space.ef_production_space
      staging_asgs.#:          "2" => "0"
      staging_asgs.1699531225: "e29315cb-ec42-4f43-b49f-49565a1b8dd8" => ""
      staging_asgs.3513182257: "15123ed0-3747-4f2f-a473-79ff0fed8e80" => ""


Plan: 0 to add, 3 to change, 0 to destroy.
```

Hope this can help.

I would be happy to contribute a test case, but unfortunately, the fix by @jcarrothers-sap in #79 is more complex that just waiting for the app to stage. I'll still try to review his code and comment in #79.

Best,
Benjamin

**Comment by janosbinder** [comment] 2018-05-31 21:14
@bgandon @jcarrothers-sap 

If you are looking for an automated test, please find this commit here https://github.com/chrismathias/terraform-provider-cf/commit/ad576d78b9082739baf39bcc95d6e502322084b2

What I do, I deploy "another version" of the cf_app, via terraform apply. (See line https://github.com/chrismathias/terraform-provider-cf/blob/ad576d78b9082739baf39bcc95d6e502322084b2/cloudfoundry/resource_cf_route_test.go#L146 and line https://github.com/chrismathias/terraform-provider-cf/blob/ad576d78b9082739baf39bcc95d6e502322084b2/cloudfoundry/resource_cf_route_test.go#L185 with the "another version")

Then you see the error, which @samedguener and @jcarrothers-sap already found. There is also some mangling with the routes, actually I am trying to reproduce another bug, but as a byproduct I found that this test case successfully covers this issue.

**Comment by janosbinder** [comment] 2018-07-04 08:30
The https://github.com/mevansam/terraform-provider-cf/pull/118 should fix the issue.

**Closed** 2018-07-09 18:52 UTC
Labels: bug
